/**
 * Réalisations vitrines Akyra — source unique pour la galerie d'accueil et la
 * page /modeles (filtrable par catégorie). Les visuels sont les aperçus
 * canoniques de public/landing/. Lien = aperçu live (démo /s/{id} ou externe).
 */
export type Realisation = {
  id: string;
  title: string;
  /** Libellé d'affichage de la catégorie. */
  category: string;
  /** Id de catégorie pour le filtre. */
  categoryId: "photographe" | "artisan" | "musicien" | "portfolio" | "saas";
  views: number;
  thumb: string;
  link: string;
  external?: boolean;
  /** Mis en avant dans la section « À la une » de l'accueil. */
  featured?: boolean;
  badge?: "PRO" | "Nouveau";
};

export const REALISATIONS: Realisation[] = [
  {
    id: "target",
    title: "Target — Magazine minimal",
    category: "Photographe",
    categoryId: "photographe",
    views: 149,
    thumb: "/landing/tpl-target.png",
    link: "/preview/target",
    external: true,
    featured: true,
    badge: "PRO",
  },
  {
    id: "potozon",
    title: "Potozon — Studio créatif",
    category: "Photographe",
    categoryId: "photographe",
    views: 153,
    thumb: "/landing/tpl-potozon.png",
    link: "/preview/potozon",
    external: true,
    featured: true,
  },
  {
    id: "alice-r",
    title: "Alice R. — Portrait éditorial",
    category: "Photographe",
    categoryId: "photographe",
    views: 159,
    thumb: "/landing/tpl-alice-r.png",
    link: "/preview/alice-r",
    external: true,
    featured: true,
    badge: "PRO",
  },
  {
    id: "arelec",
    title: "A-Relec — Électricité & chauffage",
    category: "Artisan",
    categoryId: "artisan",
    views: 132,
    thumb: "/landing/tpl-arelec.png",
    link: "https://a-relec.vercel.app",
    external: true,
    featured: true,
    badge: "Nouveau",
  },
  {
    id: "eloctix",
    title: "Eloctix — Installation électrique",
    category: "Artisan",
    categoryId: "artisan",
    views: 118,
    thumb: "/landing/tpl-eloctix-shot.png",
    link: "/#apercu",
    featured: true,
    badge: "Nouveau",
  },
  {
    id: "cleaning-services",
    title: "Ménage & services à domicile",
    category: "Artisan",
    categoryId: "artisan",
    views: 96,
    thumb: "/landing/tpl-cleaning-services.png",
    link: "/preview/cleaning-services",
    external: true,
    badge: "Nouveau",
  },
  {
    id: "eco-garden-care",
    title: "Paysagiste & entretien de jardin",
    category: "Artisan",
    categoryId: "artisan",
    views: 88,
    thumb: "/landing/tpl-eco-garden-care.png",
    link: "/preview/eco-garden-care",
    external: true,
    badge: "Nouveau",
  },
  {
    id: "creative-portfolio",
    title: "Portfolio créatif — Designer",
    category: "Portfolio",
    categoryId: "portfolio",
    views: 74,
    thumb: "/landing/tpl-creative-portfolio.png",
    link: "/preview/creative-portfolio",
    external: true,
    featured: true,
    badge: "Nouveau",
  },
  {
    id: "health-saas",
    title: "App / SaaS — Santé connectée",
    category: "SaaS",
    categoryId: "saas",
    views: 81,
    thumb: "/landing/tpl-health-saas.png",
    link: "/preview/health-saas",
    external: true,
    featured: true,
    badge: "Nouveau",
  },
  {
    id: "luxury-wedding",
    title: "Mariage premium — Studio",
    category: "Photographe",
    categoryId: "photographe",
    views: 112,
    thumb: "/landing/tpl-luxury-wedding.png",
    link: "/preview/luxury-wedding",
    external: true,
    badge: "Nouveau",
  },
  {
    id: "wedding-fine-art",
    title: "Mariage fine-art — Narratif",
    category: "Photographe",
    categoryId: "photographe",
    views: 104,
    thumb: "/landing/tpl-wedding-fine-art.png",
    link: "/preview/wedding-fine-art",
    external: true,
    badge: "Nouveau",
  },
  {
    id: "jazz-vocalist",
    title: "Marina — Vocaliste jazz & soul",
    category: "Musicien",
    categoryId: "musicien",
    views: 91,
    thumb: "/landing/tpl-jazz-vocalist.png",
    link: "/preview/jazz-vocalist",
    external: true,
    featured: true,
    badge: "Nouveau",
  },
  {
    id: "dj-electro",
    title: "Alex Stride — DJ électro",
    category: "Musicien",
    categoryId: "musicien",
    views: 87,
    thumb: "/landing/tpl-dj-electro.png",
    link: "/preview/dj-electro",
    external: true,
    featured: true,
    badge: "Nouveau",
  },
  {
    id: "electronic-collective",
    title: "Nyxis — Collectif électro",
    category: "Musicien",
    categoryId: "musicien",
    views: 79,
    thumb: "/landing/tpl-electronic-collective.png",
    link: "/preview/electronic-collective",
    external: true,
    badge: "Nouveau",
  },
  {
    id: "hiphop-producer",
    title: "Kairo — Producteur hip-hop",
    category: "Musicien",
    categoryId: "musicien",
    views: 84,
    thumb: "/landing/tpl-hiphop-producer.png",
    link: "/preview/hiphop-producer",
    external: true,
    featured: true,
    badge: "Nouveau",
  },
  {
    id: "indie-band",
    title: "Halcyon — Groupe indé",
    category: "Musicien",
    categoryId: "musicien",
    views: 76,
    thumb: "/landing/tpl-indie-band.png",
    link: "/preview/indie-band",
    external: true,
    badge: "Nouveau",
  },
  {
    id: "music-festival",
    title: "Solstice — Festival de musique",
    category: "Musicien",
    categoryId: "musicien",
    views: 95,
    thumb: "/landing/tpl-music-festival.png",
    link: "/preview/music-festival",
    external: true,
    featured: true,
    badge: "Nouveau",
  },
  {
    id: "podcast-audio",
    title: "Northwire — Podcast audio",
    category: "Musicien",
    categoryId: "musicien",
    views: 68,
    thumb: "/landing/tpl-podcast-audio.png",
    link: "/preview/podcast-audio",
    external: true,
    badge: "Nouveau",
  },
  {
    id: "plumber-pro",
    title: "Aqualis — Plombier",
    category: "Artisan",
    categoryId: "artisan",
    views: 102,
    thumb: "/landing/tpl-plumber-pro.png",
    link: "/preview/plumber-pro",
    external: true,
    featured: true,
    badge: "Nouveau",
  },
  {
    id: "plumber-modern",
    title: "BlueDrop — Plombier moderne",
    category: "Artisan",
    categoryId: "artisan",
    views: 89,
    thumb: "/landing/tpl-plumber-modern.png",
    link: "/preview/plumber-modern",
    external: true,
    badge: "Nouveau",
  },
  {
    id: "plumber-emergency",
    title: "RapidPlomb — Plombier urgence",
    category: "Artisan",
    categoryId: "artisan",
    views: 83,
    thumb: "/landing/tpl-plumber-emergency.png",
    link: "/preview/plumber-emergency",
    external: true,
    badge: "Nouveau",
  },
  {
    id: "electrician-pro",
    title: "Ohmly — Électricien",
    category: "Artisan",
    categoryId: "artisan",
    views: 97,
    thumb: "/landing/tpl-electrician-pro.png",
    link: "/preview/electrician-pro",
    external: true,
    featured: true,
    badge: "Nouveau",
  },
  {
    id: "multi-trade",
    title: "Voltéo — Élec, plomberie & chauffage",
    category: "Artisan",
    categoryId: "artisan",
    views: 91,
    thumb: "/landing/tpl-multi-trade.png",
    link: "/preview/multi-trade",
    external: true,
    badge: "Nouveau",
  },
  {
    id: "studio-portfolio",
    title: "Mörk Studio — Portfolio créatif",
    category: "Portfolio",
    categoryId: "portfolio",
    views: 78,
    thumb: "/landing/tpl-studio-portfolio.png",
    link: "/preview/studio-portfolio",
    external: true,
    featured: true,
    badge: "Nouveau",
  },
  {
    id: "analytics-saas",
    title: "Northpeak — SaaS analytics",
    category: "SaaS",
    categoryId: "saas",
    views: 86,
    thumb: "/landing/tpl-analytics-saas.png",
    link: "/preview/analytics-saas",
    external: true,
    featured: true,
    badge: "Nouveau",
  },
  {
    id: "wedding-warm",
    title: "Lumière Studio — Mariage éditorial",
    category: "Photographe",
    categoryId: "photographe",
    views: 118,
    thumb: "/landing/tpl-wedding-warm.png",
    link: "/preview/wedding-warm",
    external: true,
    featured: true,
    badge: "Nouveau",
  },
  {
    id: "portrait-fineart",
    title: "Adrien Roy — Portrait fine-art",
    category: "Photographe",
    categoryId: "photographe",
    views: 101,
    thumb: "/landing/tpl-portrait-fineart.png",
    link: "/preview/portrait-fineart",
    external: true,
    badge: "Nouveau",
  },
  {
    id: "portrait-lifestyle",
    title: "Clara Whitfield — Portrait & lifestyle",
    category: "Photographe",
    categoryId: "photographe",
    views: 94,
    thumb: "/landing/tpl-portrait-lifestyle.png",
    link: "/preview/portrait-lifestyle",
    external: true,
    badge: "Nouveau",
  },
  {
    id: "photographer-freelance",
    title: "Léon Marchal — Photographe freelance",
    category: "Photographe",
    categoryId: "photographe",
    views: 109,
    thumb: "/landing/tpl-photographer-freelance.png",
    link: "/preview/photographer-freelance",
    external: true,
    featured: true,
    badge: "Nouveau",
  },
  {
    id: "photo-vintage",
    title: "Halcyon Films — Photo vintage",
    category: "Photographe",
    categoryId: "photographe",
    views: 87,
    thumb: "/landing/tpl-photo-vintage.png",
    link: "/preview/photo-vintage",
    external: true,
    badge: "Nouveau",
  },
  {
    id: "landscape-prints",
    title: "Orin Vale — Paysage & tirages",
    category: "Photographe",
    categoryId: "photographe",
    views: 123,
    thumb: "/landing/tpl-landscape-prints.png",
    link: "/preview/landscape-prints",
    external: true,
    featured: true,
    badge: "Nouveau",
  },
];

/** Filtres de catégorie pour /modeles (dérivés des réalisations + « bientôt »). */
export const SHOWCASE_FILTERS: { id: string; label: string; soon?: boolean }[] = [
  { id: "tous", label: "Tous" },
  { id: "photographe", label: "Photographe" },
  { id: "artisan", label: "Artisan" },
  { id: "portfolio", label: "Portfolio" },
  { id: "saas", label: "SaaS" },
  { id: "musicien", label: "Musicien" },
];

export const FEATURED = REALISATIONS.filter((r) => r.featured);
