// lib/foundry/manifests.ts
import type { ComponentManifest, VibeId } from "./types";
import { VIBE_IDS } from "./vibes";
import { LIBRARY_MANIFESTS } from "./library";

// Les composants sont pilotés par les CSS vars de la vibe : ils supportent
// toutes les DA du système (la personnalité vient des tokens, pas du markup).
const ALL_VIBES: VibeId[] = VIBE_IDS;

/** Socle historique (extraction Sereenity) — la library extraite s'y ajoute. */
const CORE_MANIFESTS: Record<string, ComponentManifest> = {
  "hero-split-asym": {
    id: "hero-split-asym",
    role: "hero",
    rarity: "rare",
    description: "Hero 3 colonnes : accroche + preuve sociale (avatars) à gauche, grande photo au centre, mini-bloc + 2e photo à droite.",
    whenToUse: ["forte preuve sociale", "métier visuel/humain (coach, photographe, bien-être)", "hero riche premium"],
    vibes: ALL_VIBES,
    contentKeys: ["badge", "title", "subtitle", "cta", "ctaHref", "proofCount", "proofLabel", "image", "image2", "avatars"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "services-rows": {
    id: "services-rows",
    role: "services",
    rarity: "common",
    description: "Liste de services en grandes lignes numérotées (numéro + titre + description), séparées par des filets.",
    whenToUse: ["présenter 3 à 6 offres", "métier orienté prestations (coach, artisan)"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "items"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "testimonials-carousel": {
    id: "testimonials-carousel",
    role: "reviews",
    rarity: "common",
    description: "Carrousel de cartes-avis en défilement continu (marquee) : citation, avatar, nom, rôle.",
    whenToUse: ["au moins 3 témoignages clients", "renforcer la confiance"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "items"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "footer-columns": {
    id: "footer-columns",
    role: "footer",
    rarity: "common",
    description: "Footer en colonnes : marque + tagline, liens, contact ; barre basse copyright.",
    whenToUse: ["clôture de page (toujours)"],
    vibes: ALL_VIBES,
    // "socials" volontairement ABSENT des clés requises : présent via le sample
    // (normalisation) mais optionnel pour les recettes antérieures en base.
    contentKeys: ["brand", "tagline", "columns", "copyright"],
    allowedSkinKeys: ["surface"],
  },
  "reviews-postit-carousel": {
    id: "reviews-postit-carousel",
    role: "reviews",
    rarity: "rare",
    description: "Avis clients en marquee de « notes épinglées » : cartes blanches légèrement inclinées avec un pin coloré qui dépasse, sur un fond pinboard jaune doux. Citation, avatar, nom.",
    whenToUse: ["au moins 3 avis clients", "vouloir un bloc avis à fort parti pris design", "ambiance chaleureuse/créative"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "items"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "faq-accordion": {
    id: "faq-accordion",
    role: "faq",
    rarity: "common",
    description: "FAQ en accordéon 2 colonnes : intro (éyebrow + titre) à gauche, questions dépliables à droite (icône + qui pivote, réponse en hauteur animée).",
    whenToUse: ["lever les objections avant conversion", "4 à 6 questions fréquentes"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "items"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "cta-banner": {
    id: "cta-banner",
    role: "cta",
    rarity: "common",
    description: "Bandeau de conversion : panneau encre (image de fond optionnelle + voile), grande phrase Castoro et bouton pilule. Clôture de page.",
    whenToUse: ["pousser à l'action en fin de page", "rappeler le CTA principal"],
    vibes: ALL_VIBES,
    contentKeys: ["title", "cta"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "logo-marquee": {
    id: "logo-marquee",
    role: "logos",
    rarity: "common",
    description: "Bandeau de confiance : noms/partenaires en défilement continu (marquee), discret et atténué.",
    whenToUse: ["afficher des partenaires / médias / clients", "preuve de confiance légère sous le hero"],
    vibes: ALL_VIBES,
    contentKeys: ["items"],
    allowedSkinKeys: ["surface"],
  },
  "pricing-cards": {
    id: "pricing-cards",
    role: "pricing",
    rarity: "common",
    description: "Tarifs en 3 cartes (une vedette en encre) : nom, prix, features à coches, bouton. Clair et lisible.",
    whenToUse: ["présenter des offres/forfaits", "page ou section tarifs"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "plans"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "stats-countup": {
    id: "stats-countup",
    role: "stats",
    rarity: "rare",
    description: "Chiffres clés en grand, qui s'incrémentent de 0 à leur valeur à l'entrée dans l'écran (count-up au scroll).",
    whenToUse: ["preuve sociale chiffrée (clients, %, années)", "marquer la crédibilité"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "items"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "intro-split": {
    id: "intro-split",
    role: "about",
    rarity: "common",
    description: "Bloc à propos en 2 colonnes : image + texte (éyebrow, titre, paragraphe, liste à coches optionnelle).",
    whenToUse: ["présenter la personne / l'histoire", "section à propos", "humaniser le site"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "body", "image"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "process-steps": {
    id: "process-steps",
    role: "process",
    rarity: "common",
    description: "Étapes du parcours en 3 cartes numérotées (comment ça se passe / les étapes).",
    whenToUse: ["expliquer le déroulé / la méthode", "rassurer sur le process"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "steps"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "contact-block": {
    id: "contact-block",
    role: "contact",
    rarity: "common",
    description: "Bloc contact : titre + bouton à gauche, coordonnées (email / téléphone / adresse) à droite, sur carte crème.",
    whenToUse: ["donner les coordonnées + pousser à prendre RDV", "section ou page contact"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "email", "phone", "address", "cta"],
    allowedSkinKeys: ["accent", "surface"],
  },
  // --- Sections DESIGN (rythment et différencient les pages) ----------------
  "parallax-strip": {
    id: "parallax-strip",
    role: "media",
    rarity: "common",
    description: "Bandeau photo immersif pleine largeur : l'image glisse en parallaxe pendant le défilement, voile encre, accroche + bouton posés dessus.",
    whenToUse: ["rythmer une page entre deux sections de contenu", "métier visuel (réalisations, lieux, ambiance)", "donner du souffle design à une page"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "cta", "image"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "gallery-mosaic": {
    id: "gallery-mosaic",
    role: "gallery",
    rarity: "common",
    description: "Galerie mosaïque : photos aux hauteurs alternées en colonnes, entrée en cascade au scroll, zoom doux au survol.",
    whenToUse: ["page réalisations / portfolio / chantiers / plats", "montrer le travail en images plutôt qu'en discours"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "images"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "team-cards": {
    id: "team-cards",
    role: "team",
    rarity: "common",
    description: "L'équipe en cartes portrait : photo, nom, rôle et mot personnel, entrée en cascade.",
    whenToUse: ["page à propos / qui sommes-nous", "humaniser avec des visages", "équipe de 1 à 6 personnes"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "items"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "story-timeline": {
    id: "story-timeline",
    role: "story",
    rarity: "common",
    description: "Frise verticale (année, jalon, récit) : fil accent et pastilles, jalons qui se dévoilent au scroll.",
    whenToUse: ["raconter une histoire / un parcours (page à propos)", "montrer l'évolution d'un projet ou d'une méthode dans le temps"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "items"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "quote-spotlight": {
    id: "quote-spotlight",
    role: "statement",
    rarity: "common",
    description: "Manifeste : une seule grande citation plein cadre encre, guillemet géant accent en filigrane, auteur en signature.",
    whenToUse: ["affirmer une conviction / une devise", "respiration typographique forte entre deux sections"],
    vibes: ALL_VIBES,
    contentKeys: ["quote", "author", "role"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "marquee-words": {
    id: "marquee-words",
    role: "decor",
    rarity: "common",
    description: "Bandeau de grands mots en défilement continu, séparés par des étoiles accent — pure respiration design.",
    whenToUse: ["lister valeurs / services / villes en un bandeau vivant", "casser la monotonie entre deux sections denses"],
    vibes: ALL_VIBES,
    contentKeys: ["words"],
    allowedSkinKeys: ["accent", "surface"],
  },
  // --- Effets portés en sections (ex-marketplace « effets ») -----------------
  "fx-circular-reviews": {
    id: "fx-circular-reviews",
    role: "reviews",
    rarity: "epic",
    description: "Témoignages carrousel 3D : trois portraits empilés en perspective (centre net, voisins inclinés), citation révélée mot à mot, flèches + défilement auto. Très haut de gamme.",
    whenToUse: ["3 avis clients forts avec PORTRAITS", "bloc avis spectaculaire et premium", "métier visuel/humain"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "items"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "fx-container-scroll": {
    id: "fx-container-scroll",
    role: "media",
    rarity: "epic",
    description: "Mise en scène au scroll : une grande photo dans un cadre type écran incliné en 3D qui se redresse élégamment pendant le défilement, surmontée d'un titre géant.",
    whenToUse: ["mettre UNE photo phare en scène de façon spectaculaire", "moment wow au milieu de la page", "bloc très haut : il lui faut de la piste de défilement"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "image"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "fx-display-cards": {
    id: "fx-display-cards",
    role: "highlights",
    rarity: "rare",
    description: "Cartes en éventail : pile de 3 cartes inclinées façon cartes à jouer sur fond encre, les deux du fond voilées qui se révèlent au survol — illustre 3 temps forts.",
    whenToUse: ["3 temps forts / actualités / points de fierté", "respiration design sombre entre deux sections claires"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "items"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "fx-stagger-reviews": {
    id: "fx-stagger-reviews",
    role: "reviews",
    rarity: "rare",
    description: "Frise de témoignages : cartes carrées à coin coupé étalées depuis le centre, la centrale en couleur d'accent surélevée ; clic ou chevrons pour faire défiler. Pleine largeur, très graphique.",
    whenToUse: ["au moins 6 avis courts", "bloc avis original à fort parti pris", "remplir une pleine largeur"],
    vibes: ALL_VIBES,
    contentKeys: ["items"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "fx-shuffle-reviews": {
    id: "fx-shuffle-reviews",
    role: "reviews",
    rarity: "rare",
    description: "Témoignages à mélanger : pile de 3 cartes en éventail sur fond encre — on attrape la carte de devant et on la jette à gauche pour révéler la suivante. Ludique et mémorable.",
    whenToUse: ["3 avis à présenter de façon interactive", "site au ton joueur/créatif", "section sombre de contraste"],
    vibes: ALL_VIBES,
    contentKeys: ["eyebrow", "title", "items"],
    allowedSkinKeys: ["accent", "surface"],
  },
  "fx-floating-tags": {
    id: "fx-floating-tags",
    role: "statement",
    rarity: "rare",
    description: "Slogan flottant : une phrase-manifeste centrée entourée de pastilles de valeurs et de points qui flottent doucement — la section « valeurs » signature des sites bien-être.",
    whenToUse: ["affirmer des valeurs (4 à 8 mots-clés) autour d'une phrase", "coach / bien-être / marque humaine", "respiration aérée et vivante"],
    vibes: ALL_VIBES,
    contentKeys: ["text", "tags"],
    allowedSkinKeys: ["accent", "surface"],
  },
};

/** Catalogue complet : socle + library extraite des sites. */
export const MANIFESTS: Record<string, ComponentManifest> = {
  ...CORE_MANIFESTS,
  ...LIBRARY_MANIFESTS,
};

export function getManifest(id: string): ComponentManifest | undefined {
  return MANIFESTS[id];
}
export function listManifests(): ComponentManifest[] {
  return Object.values(MANIFESTS);
}
